language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t hackerman4047/react-test -f ./client/Dockerfile.dev
script:
    - docker run -e CI=true hackerman4047/react-test npm test
after_success:
    - docker build -t hackerman4047/multi-client ./client
    - docker build -t hackerman4047/multi-server ./server
    - docker build -t hackerman4047/multi-nginx ./nginx
    - docker build -t hackerman4047/multi-worker ./worker
    # login to docker cli
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    - docker push hackerman4047/multi-client
    - docker push hackerman4047/multi-server
    - docker push hackerman4047/multi-nginx
    - docker push hackerman4047/multi-worker
    